pimcore_content_migration:
    templates:
        migration_template: '@PimcoreContentMigration/code_templates/migration.php.twig'
        document_template: '@PimcoreContentMigration/code_templates/document.php.twig'
        asset_template: '@PimcoreContentMigration/code_templates/asset.php.twig'
        object_template: '@PimcoreContentMigration/code_templates/object.php.twig'